# 应用名称
spring:
  application:
      name: tools
  redis:
    sentinel:
      master: mymaster
      nodes: 10.0.252.38:26379,10.0.252.38:26381,10.0.252.38:26380
    password: ebiz2020
    database: 9

server:
  port: 2822
  servlet:
    context-path: /tools

logging:
  level:
    org.springframework: debug
    com.xuelei: debug


# alipay appid 2016101500691575
# alipay gateway https://openapi.alipaydev.com/gateway.do

